#+TITLE: Blockchain Courses

* [[https://www.coursera.org/learn/cryptocurrency/home/welcome][Princeton Cryptocurrency]]
** ScroogeCoin
Centralized authority validates/creates transactions. Transactions are valid if
the coins used are signed, unspent (no double spends), and output values are
non-negative and their sum is not greater than the sum of inputs.

Transactions are handled in epochs, during which some may use coins created in
that same epoch.

** Consensus
*** Protocol
1. must terminate with all honest nodes in agreement on value
2. value must have been generated by honest node
   
*** Consensus Algorithm (simplified)
/Implicit consensus/, ie. there is no consensus algorithm for selecting a block,
or any voting. Nodes implicitly accept/reject proposed blocks by choosing to
build on them or ignore them and build from previous block.

1. New transactions broadcast to all nodes
2. Each node collects new transactions into a block
3. In each round, a *random* node broadcasts its block
4. Other nodes accept new block only if all transactions are valid
5. If valid, nodes include block's hash in next block they create

*** Implementation
The grader is very strict on memory/size of messages passed between nodes.

- ~Simulation.java~ is driver program taking parameters to vary graph
  pairwise-connectivity, prob. of a given node being malicious, prob. of a node
  receiving an initial transaction, and number of rounds to propagate messages
  before consensus.

- ~CompliantNode.java~ implements implicit consensus by choosing to accept
  transactions that have been sent by large enough percentage of nodes it
  follows. Any of its followees that stop sending messages during a given epoch
  are ignored afterward. The threshold for a transaction being chosen as part of
  the consensus set varies by the graph probabilities (pairwise-connectivity,
  probability of a node receiving an initial transaction).

** Blockchain
Implement a node in a blockchain-based distribution consensus protocol that
receives incoming transactions/blocks and updates the blockchain.
